config/routes.rb
Prime::Application.routes.draw do
  resources :turn_logs
  resources :node_types
  resources :node_links
  resources :units
  resources :nodes
  resources :players
  resources :turns
  

  match 'log_in' => 'sessions#new', :as => 'log_in'
  match 'log_out' => 'sessions#destroy', :as => 'log_out'
  match 'auth' => 'sessions#create', :as => 'auth'
  match 'sign_up' => 'players#new', :as => 'sign_up'
  match 'map' => 'map#show', :as => 'map'
  match 'unit_move/:unit/:nodelink' => 'units#move', :as => 'unit_move'
  match 'unit_cancel_move/:unit' => 'units#cancel_move', :as => 'unit_cancel_move'
  match 'test_turn' => 'turns#index', :as => 'test_turn'
  

  root :to => 'welcome#index'

end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :units
  belongs_to :node_type
  has_many :node_links #intermediate result for :linked_nodes
  has_many :linked_nodes, :through => :node_links #nodes traversable from this node
  
  after_initialize :init_instance_vars
  
  def init_instance_vars
    @default_strength = 25 # strength when allegiance changes
    @minimum_strength = 1
  end
  
  def colour
    node_type.name
  end
  
  def neighbours
    linked_nodes
  end
  
  def friendly_neighbours 
    neighbours.select {|node| node.human? == self.human?}
  end
  
  def enemy_neighbours 
    neighbours.select {|node| node.human? != self.human?}
  end
  
  def change_allegiance(allegiance = !human?)
    self.update_attributes({ :is_human => allegiance, :strength => @default_strength })
  end
  
  def enemy?(unit)
    # ^ is the Ruby XOR operator
    unit && (unit.human? ^ self.human?)
  end
  
  def friends?(unit)
    unit && (unit.human? == self.human?)
  end
  
  def attackers
    units.select{ |unit| self.enemy?(unit) }
  end
  
  def defenders
    units.select { |unit| self.friends?(unit) }
  end
  
  def human?
    is_human
  end
  
  def under_attack?
    !attackers.empty?
  end
  
  def take_damage(damage = 10)
    new_strength = [self.strength - damage, @minimum_strength].max
    self.update_attributes({ :strength => new_strength })
  end
end

app/models/node_type.rb
class NodeType < ActiveRecord::Base
  has_many :nodes
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  http_basic_authenticate_with :name => "god", :password => "god", :except => :index

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.order(:id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])
	@inverse_linked_nodes = NodeLink.where("linked_node_id = '#{@node.id}'")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= image_tag(:"map.png") %>

<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :node_type_id %><br />
    <%= f.collection_select(:node_type_id, NodeType.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :strength %><br />
	<%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.label :is_human %><br />
	<%= f.text_field :is_human %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<%= image_tag(:'map.png') %>

<table border='1'>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>X</th>
    <th>Y</th>
	<th>Node Type</th>
	<th>Is Human</th>
	<th>Strength</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.id %></td>
    <td><%= node.name %></td>
    <td><%= node.x %></td>
    <td><%= node.y %></td>
	<td><%= link_to node.node_type.name, node.node_type %></td>
	<td><%= node.is_human %></td>
	<td><%= node.strength %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>

<p>
  <b>X:</b>
  <%= @node.x %>
</p>

<p>
  <b>Y:</b>
  <%= @node.y %>
</p>

<p>
  <b>Node Type:</b>
  <%= @node.node_type.name if @node.node_type %>
</p>

<p>
  <b>Strength:</b>
  <%= @node.strength %>
</p>

<p>
  <b>Is Human:</b>
  <%= @node.is_human %>
</p>

<h3>Units here</h3>

<% @node.units do |unit| %>
  <%= link_to unit.name, unit %>, 
<% end %>

<% if @node.units.empty? %>None<% end %>

<h3>From Here, Units can travel to: </h3>

<% @node.linked_nodes.each do |linked_node| %>
  <%= link_to linked_node.name, linked_node %><br />
<% end %>

<h3>Units can get here from: </h3>

<!--- [HACK] warning this is bad. Look at node controller -->
<% @inverse_linked_nodes.each do |node_linked| %>
  <%= link_to node_linked.node.name, node_linked.node %><br />
<% end %>

<p></p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>