config/routes.rb
Prime::Application.routes.draw do
  resources :turn_logs
  resources :node_types
  resources :node_links
  resources :units
  resources :nodes
  resources :players
  resources :turns
  

  match 'log_in' => 'sessions#new', :as => 'log_in'
  match 'log_out' => 'sessions#destroy', :as => 'log_out'
  match 'auth' => 'sessions#create', :as => 'auth'
  match 'sign_up' => 'players#new', :as => 'sign_up'
  match 'map' => 'map#show', :as => 'map'
  match 'unit_move/:unit/:nodelink' => 'units#move', :as => 'unit_move'
  match 'unit_cancel_move/:unit' => 'units#cancel_move', :as => 'unit_cancel_move'
  match 'test_turn' => 'turns#index', :as => 'test_turn'
  

  root :to => 'welcome#index'

end

app/models/node_link.rb
# node_id:integer linked_node_id:integer
class NodeLink < ActiveRecord::Base
  belongs_to :node
  belongs_to :linked_node, :class_name => "Node"
  has_many :units
  
  def origin
    node
  end
  
  def destination
    linked_node
  end
  
  def inverse
    inverses = NodeLink.keep_if { |link| link.node == linked_node && link.linked_node == node }
	inverses.first if inverses
  end
  
end

app/controllers/node_links_controller.rb
class NodeLinksController < ApplicationController
  http_basic_authenticate_with :name => "god", :password => "god", :except => :index

  # GET /node_links
  # GET /node_links.json
  def index
    @node_links = NodeLink.order("node_id", "linked_node_id")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @node_links }
    end
  end

  # GET /node_links/1
  # GET /node_links/1.json
  def show
    @node_link = NodeLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node_link }
    end
  end

  # GET /node_links/new
  # GET /node_links/new.json
  def new
    @node_link = NodeLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node_link }
    end
  end

  # GET /node_links/1/edit
  def edit
    @node_link = NodeLink.find(params[:id])
  end

  # POST /node_links
  # POST /node_links.json
  def create
    @node_link = NodeLink.new(params[:node_link])

    respond_to do |format|
      if @node_link.save
        format.html { redirect_to @node_link, notice: 'Node link was successfully created.' }
        format.json { render json: @node_link, status: :created, location: @node_link }
      else
        format.html { render action: "new" }
        format.json { render json: @node_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /node_links/1
  # PUT /node_links/1.json
  def update
    @node_link = NodeLink.find(params[:id])

    respond_to do |format|
      if @node_link.update_attributes(params[:node_link])
        format.html { redirect_to @node_link, notice: 'Node link was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @node_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /node_links/1
  # DELETE /node_links/1.json
  def destroy
    @node_link = NodeLink.find(params[:id])
    @node_link.destroy

    respond_to do |format|
      format.html { redirect_to node_links_url }
      format.json { head :ok }
    end
  end
end

app/helpers/node_links_helper.rb
module NodeLinksHelper
end

app/views/node_links/_form.html.erb
<%= image_tag(:"map.png") %>

<%= form_for(@node_link) do |f| %>
  <% if @node_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node_link.errors.count, "error") %> prohibited this node_link from being saved:</h2>

      <ul>
      <% @node_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :node_id %><br />
    <%= f.collection_select(:node_id, Node.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :linked_node_id %><br />
    <%= f.collection_select(:linked_node_id, Node.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/node_links/edit.html.erb
<h1>Editing node_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @node_link %> |
<%= link_to 'Back', node_links_path %>

app/views/node_links/index.html.erb
<h1>Listing node_links</h1>

<%= image_tag("map.png") %>

<p><b>Node:</b> The NodeLink with Id 0 is used to represent a unit who is not moving.
This is an invalid Id and is not a member of the database table. It is hardcoded.
</p>

<table>
  <tr>
    <th>Id</th>
    <th>Node id</th>
	<th>Node</th>
    <th>Linked node id</th>
	<th>Linked node</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @node_links.each do |node_link| %>
  <tr>
    <td><%= node_link.id %></td>
    <td><%= node_link.node_id %></td>
	<td><%= link_to node_link.node.name, node_link.node %></td>
    <td><%= node_link.linked_node_id %></td>
	<td><%= link_to node_link.linked_node.name, node_link.linked_node %></td>
    <td><%= link_to 'Show', node_link %></td>
    <td><%= link_to 'Edit', edit_node_link_path(node_link) %></td>
    <td><%= link_to 'Destroy', node_link, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node link', new_node_link_path %>

app/views/node_links/new.html.erb
<h1>New node_link</h1>
<p id='notice'><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', node_links_path %>

app/views/node_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Node:</b>
  id = <%= @node_link.node_id %><br />
  node = <%= link_to @node_link.node.name, @node_link.node %>
</p>

<p>
  <b>Linked node:</b>
  id = <%= @node_link.linked_node_id %><br />
  node = <%= link_to @node_link.linked_node.name, @node_link.linked_node %>
</p>


<%= link_to 'Edit', edit_node_link_path(@node_link) %> |
<%= link_to 'Listing', node_links_path %>