config/routes.rb
Prime::Application.routes.draw do
  resources :turn_logs
  resources :node_types
  resources :node_links
  resources :units
  resources :nodes
  resources :players
  resources :turns
  

  match 'log_in' => 'sessions#new', :as => 'log_in'
  match 'log_out' => 'sessions#destroy', :as => 'log_out'
  match 'auth' => 'sessions#create', :as => 'auth'
  match 'sign_up' => 'players#new', :as => 'sign_up'
  match 'map' => 'map#show', :as => 'map'
  match 'unit_move/:unit/:nodelink' => 'units#move', :as => 'unit_move'
  match 'unit_cancel_move/:unit' => 'units#cancel_move', :as => 'unit_cancel_move'
  match 'test_turn' => 'turns#index', :as => 'test_turn'
  

  root :to => 'welcome#index'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  extend Battle
  
  belongs_to :node
  belongs_to :player
  belongs_to :node_link #represents the link between nodes that a unit is traversing
  has_many :turn_logs
  
  @@human_home_node_id = 1 #respawn location for human units
  @@computer_home_node_id = 5 #respawn location for computer units
  
  # used to ensure a unit doesn't move (since a unit will never be at node_id 0)
  def stop
    self.update_attributes({ :node_link_id => 0})
  end

  def retreat
    # unit was defending
    if !moving?
	  strongest_friendly_neighbour = location.neighbours.select{ |node| node.human? == self.human? }.inject {|node1, node2| node1.strength > node2.strength ? node1 : node2}
	  # able to retreat to friendly node
	  if !strongest_friendly_neighbour.nil?
	    dest = strongest_friendly_neighbour
	    dest_id = strongest_friendly_neighbour.id
		verb = 'retreated to'
	  # surrounded, no friendly neighbouring node to retreat to
	  else
	    # respawn destination
	    dest_id = self.human? ? @@human_home_node_id : @@computer_home_node_id
		verb = 'respawned at'
	  end
	# unit is retreating after attacking
	else
	  # retreat back to the node from where this unit came from
	  dest = move_path.origin
	  dest_id = move_path.origin.id
	  verb = 'scattered back to'
	end
	
	dest ||= Node.find(dest_id)
	msg = "#{name} #{verb} #{dest.name}"
	log('retreat',msg)
	self.update_attributes({ :node_id => dest_id })
	
	# units retreating after a battle, can not then move	
	self.stop
  end
  
  def log(code,msg)
    l = TurnLog.new
	l.update_attributes({ :notes => msg, :unit_id => self.id, :desc => code, :when => Time.now })
  end
  
  def move(node_id = destination.id, verb = 'moved to')
    msg = "#{name} #{verb} #{Node.find(node_id).name}"
	log('move',msg)
    self.update_attributes({ :node_id => node_id})
  end
  
  def move_order(new_move_path)
    if new_move_path && (new_move_path.origin == self.location)
      msg = "#{name} will move to #{new_move_path.destination.name} from #{self.location}"
	  log('move_order', msg)
	  self.update_attributes ({ :node_link_id => new_move_path.id })
	else
	  nil #indicate that move_order failed
	end
  end
  
  def enemy?(unit)
    # ^ is the XOR operator
    self.human? ^ unit.human?
  end
    
  # a unit is moving if the unit is not yet at its destination
  # a stationary unit is also modelled as one with a node_link_id of 0 (since a unit will never be at node_id 0)
  def moving?
    move_path && (self.location != move_path.destination)
  end
    
  def self.move_all_human
    move_all true
  end
  
  def self.move_all_computer
    move_all false
  end
  
  def self.move_all(allegiance)
    Unit.select { |unit| unit.moving? && (unit.human? == allegiance)}.each { |unit| unit.move }
  end
  
  def destination
    move_path ? move_path.destination : self.location
  end
  
  # returns the name of the stat that this player is strongest with
  def strongest
    if red > blue && red > green
	  return :red
	elsif blue > red && blue > green
	  return :blue
	else
	  return :green
	end
  end
  
  def location
    node
  end
  
  def human?
    player.is_human
  end
  
  def move_path
    node_link
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  http_basic_authenticate_with :name => "god", :password => "god", :except => [ :move, :cancel_move ]
  
  def cancel_move
    @unit = current_player.units.find(params[:unit]) if current_player
	
	respond_to do |format|
	  if !@unit
	     format.html { redirect_to map_path, notice: 'Player probable does not have permission to cancel the move order' }
         format.json { render json: 'permission denied', status: :unprocessable_entry }
	  elsif @unit.stop
        format.html { redirect_to map_path, notice: "#{@unit.name} will stay at present location" }
        format.json { head :ok }
      else	  
        format.html { redirect_to map_path, notice: 'Database error, maybe node_link_id has been linked with node_links in the database?' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }	  
	  end
	end
  end
  
  def move
    @unit = current_player.units.find(params[:unit]) if current_player
	@nodelink = NodeLink.find(params[:nodelink])
	
	if @unit && @nodelink
	  move_order = "#{@unit.name} will move from #{@nodelink.node.name} to #{@nodelink.linked_node.name}"
	end
	
    respond_to do |format|
	  if !(@unit && @nodelink)
	    # node :unit and :node must exist otherwise it would not route here
	    format.html { redirect_to map_path, notice: 'Player probably does not have permission to move unit (' + params[:unit] + ') along nodelink (' + params[:nodelink] + ')'}
	    format.json { render json: 'permission denied', status: :unprocessable_entry }
	  elsif @unit.node == @nodelink.node
        if @unit.update_attributes({:node_link_id => @nodelink.id })
          format.html { redirect_to map_path, notice: 'Set order: ' + move_order }
          format.json { head :ok }
        else
          format.html { redirect_to map_path, notice: 'DB fail to save the order: ' + move_order }
          format.json { render json: @unit.errors, status: :unprocessable_entity }
        end
	  else
	    format.html { redirect_to map_path, notice: 'No direct link between nodes to allow to move ' + move_order}
		format.json { render json: @unit.errors, status: :unprocessable_entity }
	  end
    end
	
  end

  # GET /units
  # GET /units.json
  def index
    @units = Unit.order(:id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @units }
    end
  end

  # GET /units/1
  # GET /units/1.json
  def show
    @unit = Unit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/new
  # GET /units/new.json
  def new
    @unit = Unit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit }
    end
  end

  # GET /units/1/edit
  def edit
    @unit = Unit.find(params[:id])
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(params[:unit])

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render json: @unit, status: :created, location: @unit }
      else
        format.html { render action: "new" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /units/1
  # PUT /units/1.json
  def update
    @unit = Unit.find(params[:id])

    respond_to do |format|
      if @unit.update_attributes(params[:unit])
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :ok }
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :map_img %><br />
    <%= f.text_field :map_img %>
  </div>
  <div class="field">
    <%= f.label :node_id %><br />
	<%= collection_select(:unit, :node_id, Node.all, :id, :id) %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= collection_select(:unit, :player_id, Player.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :node_link_id %> <br />
	<%= f.number_field :node_link_id %> <br />
	Note, a link of 0 implies the unit is not planning to move
  </div>
  <div class="field">
    <%= f.label :red %></br />
	<%= f.number_field :red %>
  </div>
  <div class="field">
    <%= f.label :blue %></br />
	<%= f.number_field :blue %>
  </div>
  <div class="field">
    <%= f.label :green %></br />
	<%= f.number_field :green %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Map img</th>
	<th></th>
	<th>Node</th>
	<th>Node Link</th>
	<th>Red</th>
	<th>Blue</th>
	<th>Green</th>
	<th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @units.each do |unit| %>
  <tr>
    <td><%= unit.id %></td>
    <td><%= link_to unit.name, unit %></td>
    <td><%= unit.map_img %></td>
	<td><%= image_tag(unit.map_img) %></td>
	<td><%= link_to (unit.node.id.to_s + ". " + unit.node.name), unit.node %></td>
	<td>
	<% if unit.node_link.present? %>
	  <%= link_to unit.node_link.id, unit.node_link %>
	<% else %> 0 <% end %></td>
	<td><%= unit.red %></td>
	<td><%= unit.blue %></td>
	<td><%= unit.green %></td>
	<td><%= unit.player.name if unit.player %></td>
    <td><%= link_to 'Show', unit %></td>
    <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
    <td><%= link_to 'Destroy', unit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unit.name %>
</p>

<p>
  <b>Map img:</b>
  <%= @unit.map_img %>
  <%= image_tag(@unit.map_img) %>
</p>

<p>
  <b>Node:</b>
  id = <%= @unit.node_id %>
  link = <%= link_to @unit.node.name, @unit.node %>
</p>

<p>
  <b>Node Link:</b>
  <% if @unit.node_link.present? %>
     id = <%= @unit.node_link.id %>, 
	 from <%= link_to @unit.node_link.node.name, @unit.node_link.node %>
	 to <%= link_to @unit.node_link.linked_node.name, @unit.node_link.linked_node %>
  <% else %>
    This unit is not travelling
  <% end %>
</p>

<p>
  <b>Player:</b>
  <%= @unit.player.name if @unit.player %>
</p>
<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>