config/routes.rb
Prime::Application.routes.draw do
  resources :turn_logs
  resources :node_types
  resources :node_links
  resources :units
  resources :nodes
  resources :players
  resources :turns
  

  match 'log_in' => 'sessions#new', :as => 'log_in'
  match 'log_out' => 'sessions#destroy', :as => 'log_out'
  match 'auth' => 'sessions#create', :as => 'auth'
  match 'sign_up' => 'players#new', :as => 'sign_up'
  match 'map' => 'map#show', :as => 'map'
  match 'unit_move/:unit/:nodelink' => 'units#move', :as => 'unit_move'
  match 'unit_cancel_move/:unit' => 'units#cancel_move', :as => 'unit_cancel_move'
  match 'test_turn' => 'turns#index', :as => 'test_turn'
  

  root :to => 'welcome#index'

end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def show
    @battle_reports = TurnLog.order('created_at DESC')
	@message_seperator = "|"
	@nodes = Node.find(:all)
	@units = Unit.find(:all)
	if current_player.present? 
	  @current_unit = current_player.units.first
	  @nodelinks = @current_unit.node.node_links
	end
  end

end

app/views/map/_battle_report.html.erb
<% x ||= 20 %>
<% y ||= 450 %>

<div style="
    position: absolute;
	left: <%= x %>px;
	top: <%= y %>px;
	z-index: 2;
	background-color:#fff0f0;
  ">
  Currently showing all logs for testing purposes, hence some duplication
  <br/>
  Note that margin = attacker strength - defender strength. So a negative margin means the attacker failed.
  <hr />
  <% if @battle_reports %>
    <% @battle_reports.each do |battle_report| %>
      <b><%= battle_report.when.strftime("%a %d-%b %H:%M ") %></b>
	  | (<i><%= battle_report.desc %></i>)
	  <%= battle_report.notes %>
	  <hr />
    <% end %>
  <% end %>
</div>

app/views/map/_map.html.erb
<% radius = 20 # radius of clickable area around the centre of nodes %>
<% x ||= 20 # left margin of map, default to 20 %>
<% y ||= 40 # top margin of map, default to 40 %>
<% magic_display_tweek = radius*-0.75 #### <-- needs investigating! %>
<% offset_x = x + magic_display_tweek %>
<% offset_y = y + magic_display_tweek %>

<!--- 
 z-index: 1 ......... map background
 z-index: 2 ......... player nodes
 z-index: 3 ......... selectable picture
 z-index: 4 ......... unit icons
 z-index: 5 ......... strength markers
-->

<!--- Place the unit banners on the map --->
<% unit_text_x = 0 - (radius/2) %>
<% unit_text_y = 20 %>
<% @units.each do |unit| %>
  <div class='unit' id='unit_<%= unit.id %>'
    style="
	  position: absolute;
	  left: <%= unit.node.x + x - (radius/2) %>px;
	  top: <%= unit.node.y + y - (radius/2) %>px;
	  z-index: 4
    ">
  <% if unit != current_unit %>
    <img src='<%= image_path("#{unit.map_img}") %>' /> 
  <% else %> 
    <img src='<%= image_path("#{unit.map_img}") %>' class='currentunit' />
  <% end %>
  </div>
  
  <!--- Place the text of the units strongest colour underneath --->
  <div class='strength_<%= unit.strongest %>_text'
  style="
    position: absolute;
	left: <%= x + unit.node.x + unit_text_x %>px;
	top:  <%= y + unit.node.y + unit_text_y %>px;
	z-index: 5
  ">
  <%= unit[unit.strongest] %>
  </div>
<% end %>

<!---- Place the background map --->
<div class='map'
  style="
	position: absolute;
	left: <%= x %>px;
	top: <%= y %>px;
	z-index: 1
  ">
  <img src='<%= image_path(:"map.png") %>' border='1' />
  
  <!--- Place the text next to the node & show white nodes --->
  <% text_x = 20 %>
  <% text_y = 0 %>
  <% @nodes.each do |node| %>
    <div class='strength_<%= node.node_type.name %>_text' id='node<%= node.id %>' 
	style="
	  position: absolute;
	  left: <%= node.x + text_x %>px;
	  top: <%= node.y + text_y %>px;
	  z-index: 5
	">
	  <%= node.strength %>
	</div>
	
	<% if node.is_human %>
	  <div
	  style="
	    position: absolute;
	    left: <%= node.x - 15 %>px;
	    top: <%= node.y - 15 %>px;
	    z-index: 2
	  ">
	    <%= image_tag(:"node_white.png") %>
	  </div>
	<% end %>
  <% end%>
</div>

<!--- Place the unit move links on where current unit can move to --->
<% if current_player.present? %>
  <% @nodelinks.each do |nodelink| %>
     <div class='reachablenode'
	 style="
	   position: absolute;
	   left: <%= nodelink.linked_node.x + offset_x %>px;
	   top: <%= nodelink.linked_node.y + offset_y %>px;
	   z-index: 2
	 ">
	    <a href='unit_move/<%= @current_unit.id %>/<%= nodelink.id %>'>
	      <img src='<%= image_path(nodelink.linked_node.node_type.reachable_img) %>' />
		</a>
	 </div>
  <% end %>

<% end %>

app/views/map/_player.html.erb
<% x ||= 20 %>
<% y ||= 0 %>

<div style="
    position: absolute;
	left: <%= x %>px;
	top: <%= y %>px;
	z-index: 2
  ">
<p>
<% if current_player %>
  logged in as <%= current_player.name %>
  <%= link_to "Logout", log_out_path %>

<% else %>
  not logged in
  <%= link_to "Login", log_in_path %>
  <%= link_to "Sign up", sign_up_path %>
<% end %>

</p>
</div>

app/views/map/_unit_orders.html.erb
<% x ||= 1000 %>
<% y ||= 20 %>

<div style="
    position: absolute;
	left: <%= x %>px;
	top: <%= y %>px;
	z-index: 2
  ">
  <table>
    <tr>
	  <th></th>
	  <th></th>
	  <th></th>
	  <th></th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>
  <% @units.each do |unit| %>
    <tr>
      <td><%= image_tag(unit.map_img) %></td>
	  <td><%= unit.name %></td>
	  <td>
	    <% if unit.node_link %>
	      moving to <%= unit.node_link.linked_node.name %> from <%= unit.node_link.node.name %> 
	    <% else %>
	      at <%= unit.node.name %>
	    <% end %>
	  </td>
	  <td>
	    <% if unit == current_unit && unit.node_link %>
		  <%= link_to "Cancel order", unit_cancel_move_path(unit) %>
		<% end %>
	  </td>
	  <td><div class='strength_red_text'>  <%= unit.red   %></div></td>
	  <td><div class='strength_blue_text'> <%= unit.blue  %></div></td>
	  <td><div class='strength_green_text'><%= unit.green %></div></td>
  <% end %>
  </table>
</div>

app/views/map/show.html.erb
<%= render :partial => 'player',        :locals => { :x => 20,   :y => 0 } %>
<%= render :partial => 'map',           :locals => { :x => 20,   :y => 40,  :current_unit => @current_unit } %>
<%= render :partial => 'unit_orders',   :locals => { :x => 1000, :y => 20,  :current_unit => @current_unit } %>
<%= render :partial => 'battle_report', :locals => { :x => 20,   :y => 450, :battle_report => @battle_report } %>

<% under_map_x = 20 %>
<% under_map_y = 400 %>

<div
  style="
    position: absolute;
	left: <%= under_map_x %>px;
	top: <%= under_map_y %>px;
	z-index: 1
  ">
  <p>
    <%= link_to "Trigger Server Turn Update", test_turn_path %>
	This link is used for testing purposes to simulate $turn_length amount of time passing.
  </p>

</div>

<% notice_x = 400 %>
<% notice_y = 0 %>

<div
  style="
    position: absolute;
	left: <%= notice_x %>px;
	top: <%= notice_y %>px;
	z-index: 2
  ">
  <p id="notice"><%= notice %></p>
</div>